### ISSUE TITLE
Asking for licence

### ISSUE THREAD

**Issue by 0xAnsR** [Err0r-ICA/Venomsploit#1]
Asking for licence

**Comment by maswerty94** [comment]
It's asking for an admin license, where can we request one?

**Comment by Python1001dz** [comment]
License required!!!!!!!

**Comment by Zup1993** [comment]
F**k, Wow, you have to type listen to use it? This is a disguised charge.

**Comment by TRAPZZY** [comment]
atleast let us know, where we can contact the adim too get the lineces

**Comment by Err0r-ICA** [comment]
DM: https://t.me/Err0r_HB
